### ISSUE TITLE
brew install zathura-pdf-mupdf fails

### ISSUE THREAD

**Issue by emninger** [zegervdv/homebrew-zathura#66]
When i try to install zathura-mupdf i get this error:

```
In file included from ../zathura-pdf-mupdf/image.c:7:
../zathura-pdf-mupdf/plugin.h:9:10: fatal error: 'zathura/plugin-api.h' file not found
#include <zathura/plugin-api.h>
```

**Comment by zegervdv** [comment]
I've just pushed the 0.3.6 update for the mupdf plugin which I hope should solve this issue.

**Comment by abcarvalho** [comment]
I'm running into the following problem with version 0.3.6:
 
```sh
❯ brew install zathura-pdf-mupdf
==> Installing zathura-pdf-mupdf from zegervdv/zathura
==> Downloading https://mupdf.com/downloads/archive/mupdf-1.16.0-source.tar.xz
######################################################################## 100.0%
Warning: Cannot verify integrity of '043a592b3b90432a5ee218d867da9aaeb0d83f99a8d9b6a638318170018c2f37--mupdf-1.16.0-source.tar.xz'.
No checksum was provided for this resource.
For your reference, the checksum is:
  sha256 "d28906cea4f602ced98f0b08d04138a9a4ac2e5462effa8c45f86c0816ab1da4"
==> Downloading https://github.com/pwmt/zathura-pdf-mupdf/archive/0.3.6.tar.gz
==> Downloading from https://codeload.github.com/pwmt/zathura-pdf-mupdf/tar.gz/0.3.6
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: c6287d9201677a2ad580452820ecf19b7b4acdc8fd31b56fec595097e6197be4
  Actual: 94ab90b367c04e3a9dda52e3587e257e4c825b375bde13032f81b1f84becb4f1
    File: ../Library/Caches/Homebrew/downloads/4cab0906e69aad193ca8622c52fa274962566ec6bafd253f73b147263576d998--zathura-pdf-mupdf-0.3.6.tar.gz
To retry an incomplete download, remove the file above.
```

**Comment by zegervdv** [comment]
Used the wrong package to calculate the hash for. Should be fixed now

**Comment by abcarvalho** [comment]
Thanks! Unfortunately, now it won't build: 

```zsh
==> Installing dependencies for zegervdv/zathura/zathura-pdf-mupdf: zathura-mupdf
==> Installing zegervdv/zathura/zathura-pdf-mupdf dependency: zathura-mupdf
==> make install build=release verbose=yes CC=clang prefix=/usr/local/Cellar/zathura-mupdf/1.16.0
🍺  /usr/local/Cellar/zathura-mupdf/1.16.0: 117 files, 151.6MB, built in 50 seconds
==> Installing zegervdv/zathura/zathura-pdf-mupdf
==> mkdir build
==> meson build --prefix /usr/local/Cellar/zathura-pdf-mupdf/0.3.6
==> cd build && ninja && ninja install
Last 15 lines from ../Library/Logs/Homebrew/zathura-pdf-mupdf/03.cd:
[6/11] Compiling C object libpdf-mupdf.dylib.p/zathura-pdf-mupdf_links.c.o
FAILED: libpdf-mupdf.dylib.p/zathura-pdf-mupdf_links.c.o
clang -Ilibpdf-mupdf.dylib.p -I. -I.. -I/usr/local/Cellar/libffi/3.3/include -I/usr/local/Cellar/pcre/8.44/include -I/usr/local/Cellar/glib/2.66.2_1/include/gio-unix-2.0 -I/usr/local/Cellar/glib/2.66.2_1/include -I/usr/local/Cellar/glib/2.66.2_1/include/glib-2.0 -I/usr/local/Cellar/glib/2.66.2_1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/atk/2.36.0/include/atk-1.0 -I/usr/local/Cellar/libpng/1.6.37/include/libpng16 -I/usr/local/Cellar/gdk-pixbuf/2.42.2/include/gdk-pixbuf-2.0 -I/usr/local/Cellar/libepoxy/1.5.4_1/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.13.1/include -I/usr/local/Cellar/pixman/0.40.0/include/pixman-1 -I/usr/local/Cellar/cairo/1.16.0_3/include/cairo -I/usr/local/Cellar/fribidi/1.0.10/include/fribidi -I/usr/local/Cellar/graphite2/1.3.14/include -I/usr/local/Cellar/harfbuzz/2.7.2/include/harfbuzz -I/usr/local/Cellar/pango/1.48.0/include/pango-1.0 -I/usr/local/Cellar/gtk+3/3.24.24/include/gtk-3.0 -I/usr/local/Cellar/girara/0.3.5/include -I/usr/local/Cellar/zathura/0.4.7/include -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -Wextra -Wpedantic -std=c11 -g -DVERSION_MAJOR=0 -DVERSION_MINOR=3 -DVERSION_REV=6 -D_DEFAULT_SOURCE -Werror=implicit-function-declaration -Werror=vla -fvisibility=hidden -MD -MQ libpdf-mupdf.dylib.p/zathura-pdf-mupdf_links.c.o -MF libpdf-mupdf.dylib.p/zathura-pdf-mupdf_links.c.o.d -o libpdf-mupdf.dylib.p/zathura-pdf-mupdf_links.c.o -c ../zathura-pdf-mupdf/links.c
../zathura-pdf-mupdf/links.c:57:7: error: use of undeclared identifier 'fz_location'
      fz_location location = fz_resolve_link(mupdf_document->ctx, mupdf_document->document, link->uri, &x, &y);
      ^
../zathura-pdf-mupdf/links.c:61:33: error: use of undeclared identifier 'location'
      target.page_number      = location.page;
                                ^
2 errors generated.
[7/11] Compiling C object libpdf-mupdf.dylib.p/zathura-pdf-mupdf_search.c.o
[8/11] Compiling C object libpdf-mupdf.dylib.p/zathura-pdf-mupdf_render.c.o
[9/11] Compiling C object libpdf-mupdf.dylib.p/zathura-pdf-mupdf_image.c.o
[10/11] Compiling C object libpdf-mupdf.dylib.p/zathura-pdf-mupdf_document.c.o
ninja: build stopped: subcommand failed.
```

**Comment by zegervdv** [comment]
This seems the same issue as in #52, but you are using the correct version of mupdf (1.16.0).

Can you remove your mupdf install and try again? Maybe it is still trying to link to the newer mupdf version?

**Comment by abcarvalho** [comment]
Thanks, @zegervdv. I uninstalled the dependency, but I'm still getting the error. :/

```zsh
❯ brew uninstall zathura && brew uninstall zathura-mupdf
Uninstalling /usr/local/Cellar/zathura/0.4.7... (52 files, 758.1KB)
Uninstalling /usr/local/Cellar/zathura-mupdf/1.16.0... (117 files, 151.6MB)
❯ brew cleanup --prune 0
Warning: Skipping p11-kit: most recent version 0.23.22 not installed
Removing: ../Library/Caches/Homebrew/all_commands_list.txt... (1.2KB)
Removing: ../Library/Caches/Homebrew/zathura-mupdf--1.16.0.tar.xz... (43.7MB)
Removing: ../Library/Caches/Homebrew/zathura--0.4.7.tar.gz... (195.2KB)
Removing: ../Library/Caches/Homebrew/zathura-pdf-mupdf--0.3.6.tar.gz... (8.7KB)
Removing: ../Library/Logs/Homebrew/zathura-mupdf... (3 files, 1MB)
Removing: ../Library/Logs/Homebrew/zathura... (6 files, 195.9KB)
Removing: ../Library/Logs/Homebrew/zathura-pdf-mupdf... (6 files, 90.6KB)
❯ brew install zathura && brew install zathura-pdf-mupdf
==> Installing zathura from zegervdv/zathura
==> Downloading https://github.com/pwmt/zathura/archive/0.4.7.tar.gz
==> Downloading from https://codeload.github.com/pwmt/zathura/tar.gz/0.4.7
######################################################################## 100.0%
==> mkdir build
==> meson build --prefix /usr/local/Cellar/zathura/0.4.7
==> cd build && ninja && ninja install
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/zathura/0.4.7: 52 files, 758.1KB, built in 15 seconds
==> Installing zathura-pdf-mupdf from zegervdv/zathura
==> Downloading https://mupdf.com/downloads/archive/mupdf-1.16.0-source.tar.xz
######################################################################## 100.0%
Warning: Cannot verify integrity of '043a592b3b90432a5ee218d867da9aaeb0d83f99a8d9b6a638318170018c2f37--mupdf-1.16.0-source.tar.xz'.
No checksum was provided for this resource.
For your reference, the checksum is:
  sha256 "d28906cea4f602ced98f0b08d04138a9a4ac2e5462effa8c45f86c0816ab1da4"
==> Downloading https://github.com/pwmt/zathura-pdf-mupdf/archive/0.3.6.tar.gz
==> Downloading from https://codeload.github.com/pwmt/zathura-pdf-mupdf/tar.gz/0.3.6
######################################################################## 100.0%
==> Installing dependencies for zegervdv/zathura/zathura-pdf-mupdf: zathura-mupdf
==> Installing zegervdv/zathura/zathura-pdf-mupdf dependency: zathura-mupdf
==> make install build=release verbose=yes CC=clang prefix=/usr/local/Cellar/zathura-mupdf/1.16.0
🍺  /usr/local/Cellar/zathura-mupdf/1.16.0: 117 files, 151.6MB, built in 48 seconds
==> Installing zegervdv/zathura/zathura-pdf-mupdf
==> mkdir build
==> meson build --prefix /usr/local/Cellar/zathura-pdf-mupdf/0.3.6
==> cd build && ninja && ninja install
Last 15 lines from ../Library/Logs/Homebrew/zathura-pdf-mupdf/03.cd:
[6/11] Compiling C object libpdf-mupdf.dylib.p/zathura-pdf-mupdf_links.c.o
FAILED: libpdf-mupdf.dylib.p/zathura-pdf-mupdf_links.c.o
clang -Ilibpdf-mupdf.dylib.p -I. -I.. -I/usr/local/Cellar/libffi/3.3/include -I/usr/local/Cellar/pcre/8.44/include -I/usr/local/Cellar/glib/2.66.2_1/include/gio-unix-2.0 -I/usr/local/Cellar/glib/2.66.2_1/include -I/usr/local/Cellar/glib/2.66.2_1/include/glib-2.0 -I/usr/local/Cellar/glib/2.66.2_1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/atk/2.36.0/include/atk-1.0 -I/usr/local/Cellar/libpng/1.6.37/include/libpng16 -I/usr/local/Cellar/gdk-pixbuf/2.42.2/include/gdk-pixbuf-2.0 -I/usr/local/Cellar/libepoxy/1.5.4_1/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.13.1/include -I/usr/local/Cellar/pixman/0.40.0/include/pixman-1 -I/usr/local/Cellar/cairo/1.16.0_3/include/cairo -I/usr/local/Cellar/fribidi/1.0.10/include/fribidi -I/usr/local/Cellar/graphite2/1.3.14/include -I/usr/local/Cellar/harfbuzz/2.7.2/include/harfbuzz -I/usr/local/Cellar/pango/1.48.0/include/pango-1.0 -I/usr/local/Cellar/gtk+3/3.24.24/include/gtk-3.0 -I/usr/local/Cellar/girara/0.3.5/include -I/usr/local/Cellar/zathura/0.4.7/include -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -Wextra -Wpedantic -std=c11 -g -DVERSION_MAJOR=0 -DVERSION_MINOR=3 -DVERSION_REV=6 -D_DEFAULT_SOURCE -Werror=implicit-function-declaration -Werror=vla -fvisibility=hidden -MD -MQ libpdf-mupdf.dylib.p/zathura-pdf-mupdf_links.c.o -MF libpdf-mupdf.dylib.p/zathura-pdf-mupdf_links.c.o.d -o libpdf-mupdf.dylib.p/zathura-pdf-mupdf_links.c.o -c ../zathura-pdf-mupdf/links.c
../zathura-pdf-mupdf/links.c:57:7: error: use of undeclared identifier 'fz_location'
      fz_location location = fz_resolve_link(mupdf_document->ctx, mupdf_document->document, link->uri, &x, &y);
      ^
../zathura-pdf-mupdf/links.c:61:33: error: use of undeclared identifier 'location'
      target.page_number      = location.page;
                                ^
2 errors generated.
[7/11] Compiling C object libpdf-mupdf.dylib.p/zathura-pdf-mupdf_search.c.o
[8/11] Compiling C object libpdf-mupdf.dylib.p/zathura-pdf-mupdf_image.c.o
[9/11] Compiling C object libpdf-mupdf.dylib.p/zathura-pdf-mupdf_render.c.o
[10/11] Compiling C object libpdf-mupdf.dylib.p/zathura-pdf-mupdf_document.c.o
ninja: build stopped: subcommand failed.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/zegervdv/homebrew-zathura/issues

These open issues may also help:
brew install zathura-pdf-mupdf fails https://github.com/zegervdv/homebrew-zathura/issues/66
```

**Comment by abcarvalho** [comment]
That did it, @zegervdv. I had to link the mupdf install with `brew link mupdf` and follow the instructions at the end. Thanks a lot!

Here's the full log:

```zsh
❯ brew edit zathura-pdf-mupdf
Editing /usr/local/Homebrew/Library/Taps/zegervdv/homebrew-zathura/zathura-pdf-mupdf.rb
❯ brew install zathura && brew install zathura-pdf-mupdf
==> Installing zathura from zegervdv/zathura
==> Downloading https://github.com/pwmt/zathura/archive/0.4.7.tar.gz
==> Downloading from https://codeload.github.com/pwmt/zathura/tar.gz/0.4.7
######################################################################## 100.0%
==> mkdir build
==> meson build --prefix /usr/local/Cellar/zathura/0.4.7
==> cd build && ninja && ninja install
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/zathura/0.4.7: 52 files, 758.2KB, built in 19 seconds
==> Installing zathura-pdf-mupdf from zegervdv/zathura
==> Downloading https://github.com/pwmt/zathura-pdf-mupdf/archive/0.3.6.tar.gz
==> Downloading from https://codeload.github.com/pwmt/zathura-pdf-mupdf/tar.gz/0.3.6
######################################################################## 100.0%
==> mkdir build
==> meson build --prefix /usr/local/Cellar/zathura-pdf-mupdf/0.3.6
Last 15 lines from ../Library/Logs/Homebrew/zathura-pdf-mupdf/02.0.3.6:
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config (0.29.2)
Using 'PKG_CONFIG_PATH' from environment with value: '/usr/local/opt/libmagic/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig:/usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/opt/readline/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/python@3.9/lib/pkgconfig:/usr/local/opt/glib/lib/pkgconfig:/usr/local/opt/atk/lib/pkgconfig:/usr/local/opt/jpeg/lib/pkgconfig:/usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/libtiff/lib/pkgconfig:/usr/local/opt/gdk-pixbuf/lib/pkgconfig:/usr/local/opt/libepoxy/lib/pkgconfig:/usr/local/opt/freetype/lib/pkgconfig:/usr/local/opt/fontconfig/lib/pkgconfig:/usr/local/opt/lzo/lib/pkgconfig:/usr/local/opt/pixman/lib/pkgconfig:/usr/local/opt/cairo/lib/pkgconfig:/usr/local/opt/fribidi/lib/pkgconfig:/usr/local/opt/gobject-introspection/lib/pkgconfig:/usr/local/opt/graphite2/lib/pkgconfig:/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/harfbuzz/lib/pkgconfig:/usr/local/opt/pango/lib/pkgconfig:/usr/local/opt/gtk+3/lib/pkgconfig:/usr/local/opt/gtk+/lib/pkgconfig:/usr/local/opt/gtk-mac-integration/lib/pkgconfig:/usr/local/opt/libnotify/lib/pkgconfig:/usr/local/opt/girara/lib/pkgconfig:/usr/local/opt/librsvg/lib/pkgconfig:/usr/local/opt/zathura/lib/pkgconfig:/usr/local/opt/libpthread-stubs/lib/pkgconfig:/usr/local/opt/libxau/lib/pkgconfig:/usr/local/opt/libxdmcp/lib/pkgconfig:/usr/local/opt/libxcb/lib/pkgconfig:/usr/local/opt/libx11/lib/pkgconfig:/usr/local/opt/libxext/lib/pkgconfig:/usr/local/opt/libxfixes/lib/pkgconfig:/usr/local/opt/libxi/lib/pkgconfig:/usr/local/opt/libxrender/lib/pkgconfig:/usr/local/opt/libxrandr/lib/pkgconfig:/usr/local/opt/libxxf86vm/lib/pkgconfig:/usr/local/opt/expat/lib/pkgconfig:/usr/local/opt/libxdamage/lib/pkgconfig:/usr/local/opt/mesa/lib/pkgconfig:/usr/local/opt/freeglut/lib/pkgconfig:/usr/local/opt/gsettings-desktop-schemas/share/pkgconfig:/usr/local/opt/adwaita-icon-theme/share/pkgconfig:/usr/local/opt/xorgproto/share/pkgconfig'
Run-time dependency zathura found: YES 0.4.7
Using 'PKG_CONFIG_PATH' from environment with value: '/usr/local/opt/libmagic/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig:/usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/opt/readline/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/python@3.9/lib/pkgconfig:/usr/local/opt/glib/lib/pkgconfig:/usr/local/opt/atk/lib/pkgconfig:/usr/local/opt/jpeg/lib/pkgconfig:/usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/libtiff/lib/pkgconfig:/usr/local/opt/gdk-pixbuf/lib/pkgconfig:/usr/local/opt/libepoxy/lib/pkgconfig:/usr/local/opt/freetype/lib/pkgconfig:/usr/local/opt/fontconfig/lib/pkgconfig:/usr/local/opt/lzo/lib/pkgconfig:/usr/local/opt/pixman/lib/pkgconfig:/usr/local/opt/cairo/lib/pkgconfig:/usr/local/opt/fribidi/lib/pkgconfig:/usr/local/opt/gobject-introspection/lib/pkgconfig:/usr/local/opt/graphite2/lib/pkgconfig:/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/harfbuzz/lib/pkgconfig:/usr/local/opt/pango/lib/pkgconfig:/usr/local/opt/gtk+3/lib/pkgconfig:/usr/local/opt/gtk+/lib/pkgconfig:/usr/local/opt/gtk-mac-integration/lib/pkgconfig:/usr/local/opt/libnotify/lib/pkgconfig:/usr/local/opt/girara/lib/pkgconfig:/usr/local/opt/librsvg/lib/pkgconfig:/usr/local/opt/zathura/lib/pkgconfig:/usr/local/opt/libpthread-stubs/lib/pkgconfig:/usr/local/opt/libxau/lib/pkgconfig:/usr/local/opt/libxdmcp/lib/pkgconfig:/usr/local/opt/libxcb/lib/pkgconfig:/usr/local/opt/libx11/lib/pkgconfig:/usr/local/opt/libxext/lib/pkgconfig:/usr/local/opt/libxfixes/lib/pkgconfig:/usr/local/opt/libxi/lib/pkgconfig:/usr/local/opt/libxrender/lib/pkgconfig:/usr/local/opt/libxrandr/lib/pkgconfig:/usr/local/opt/libxxf86vm/lib/pkgconfig:/usr/local/opt/expat/lib/pkgconfig:/usr/local/opt/libxdamage/lib/pkgconfig:/usr/local/opt/mesa/lib/pkgconfig:/usr/local/opt/freeglut/lib/pkgconfig:/usr/local/opt/gsettings-desktop-schemas/share/pkgconfig:/usr/local/opt/adwaita-icon-theme/share/pkgconfig:/usr/local/opt/xorgproto/share/pkgconfig'
Run-time dependency girara-gtk3 found: YES 0.3.5
Using 'PKG_CONFIG_PATH' from environment with value: '/usr/local/opt/libmagic/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig:/usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/opt/readline/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/python@3.9/lib/pkgconfig:/usr/local/opt/glib/lib/pkgconfig:/usr/local/opt/atk/lib/pkgconfig:/usr/local/opt/jpeg/lib/pkgconfig:/usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/libtiff/lib/pkgconfig:/usr/local/opt/gdk-pixbuf/lib/pkgconfig:/usr/local/opt/libepoxy/lib/pkgconfig:/usr/local/opt/freetype/lib/pkgconfig:/usr/local/opt/fontconfig/lib/pkgconfig:/usr/local/opt/lzo/lib/pkgconfig:/usr/local/opt/pixman/lib/pkgconfig:/usr/local/opt/cairo/lib/pkgconfig:/usr/local/opt/fribidi/lib/pkgconfig:/usr/local/opt/gobject-introspection/lib/pkgconfig:/usr/local/opt/graphite2/lib/pkgconfig:/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/harfbuzz/lib/pkgconfig:/usr/local/opt/pango/lib/pkgconfig:/usr/local/opt/gtk+3/lib/pkgconfig:/usr/local/opt/gtk+/lib/pkgconfig:/usr/local/opt/gtk-mac-integration/lib/pkgconfig:/usr/local/opt/libnotify/lib/pkgconfig:/usr/local/opt/girara/lib/pkgconfig:/usr/local/opt/librsvg/lib/pkgconfig:/usr/local/opt/zathura/lib/pkgconfig:/usr/local/opt/libpthread-stubs/lib/pkgconfig:/usr/local/opt/libxau/lib/pkgconfig:/usr/local/opt/libxdmcp/lib/pkgconfig:/usr/local/opt/libxcb/lib/pkgconfig:/usr/local/opt/libx11/lib/pkgconfig:/usr/local/opt/libxext/lib/pkgconfig:/usr/local/opt/libxfixes/lib/pkgconfig:/usr/local/opt/libxi/lib/pkgconfig:/usr/local/opt/libxrender/lib/pkgconfig:/usr/local/opt/libxrandr/lib/pkgconfig:/usr/local/opt/libxxf86vm/lib/pkgconfig:/usr/local/opt/expat/lib/pkgconfig:/usr/local/opt/libxdamage/lib/pkgconfig:/usr/local/opt/mesa/lib/pkgconfig:/usr/local/opt/freeglut/lib/pkgconfig:/usr/local/opt/gsettings-desktop-schemas/share/pkgconfig:/usr/local/opt/adwaita-icon-theme/share/pkgconfig:/usr/local/opt/xorgproto/share/pkgconfig'
Run-time dependency glib-2.0 found: YES 2.66.2
Using 'PKG_CONFIG_PATH' from environment with value: '/usr/local/opt/libmagic/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig:/usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/opt/readline/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/python@3.9/lib/pkgconfig:/usr/local/opt/glib/lib/pkgconfig:/usr/local/opt/atk/lib/pkgconfig:/usr/local/opt/jpeg/lib/pkgconfig:/usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/libtiff/lib/pkgconfig:/usr/local/opt/gdk-pixbuf/lib/pkgconfig:/usr/local/opt/libepoxy/lib/pkgconfig:/usr/local/opt/freetype/lib/pkgconfig:/usr/local/opt/fontconfig/lib/pkgconfig:/usr/local/opt/lzo/lib/pkgconfig:/usr/local/opt/pixman/lib/pkgconfig:/usr/local/opt/cairo/lib/pkgconfig:/usr/local/opt/fribidi/lib/pkgconfig:/usr/local/opt/gobject-introspection/lib/pkgconfig:/usr/local/opt/graphite2/lib/pkgconfig:/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/harfbuzz/lib/pkgconfig:/usr/local/opt/pango/lib/pkgconfig:/usr/local/opt/gtk+3/lib/pkgconfig:/usr/local/opt/gtk+/lib/pkgconfig:/usr/local/opt/gtk-mac-integration/lib/pkgconfig:/usr/local/opt/libnotify/lib/pkgconfig:/usr/local/opt/girara/lib/pkgconfig:/usr/local/opt/librsvg/lib/pkgconfig:/usr/local/opt/zathura/lib/pkgconfig:/usr/local/opt/libpthread-stubs/lib/pkgconfig:/usr/local/opt/libxau/lib/pkgconfig:/usr/local/opt/libxdmcp/lib/pkgconfig:/usr/local/opt/libxcb/lib/pkgconfig:/usr/local/opt/libx11/lib/pkgconfig:/usr/local/opt/libxext/lib/pkgconfig:/usr/local/opt/libxfixes/lib/pkgconfig:/usr/local/opt/libxi/lib/pkgconfig:/usr/local/opt/libxrender/lib/pkgconfig:/usr/local/opt/libxrandr/lib/pkgconfig:/usr/local/opt/libxxf86vm/lib/pkgconfig:/usr/local/opt/expat/lib/pkgconfig:/usr/local/opt/libxdamage/lib/pkgconfig:/usr/local/opt/mesa/lib/pkgconfig:/usr/local/opt/freeglut/lib/pkgconfig:/usr/local/opt/gsettings-desktop-schemas/share/pkgconfig:/usr/local/opt/adwaita-icon-theme/share/pkgconfig:/usr/local/opt/xorgproto/share/pkgconfig'
Run-time dependency cairo found: YES 1.16.0

meson.build:22:0: ERROR: C shared or static library 'mupdf' not found

A full log can be found at /private/tmp/zathura-pdf-mupdf-20201215-15202-hyqjg8/zathura-pdf-mupdf-0.3.6/build/meson-logs/meson-log.txt

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/zegervdv/homebrew-zathura/issues

These open issues may also help:
brew install zathura-pdf-mupdf fails https://github.com/zegervdv/homebrew-zathura/issues/66
❯ brew install mupdf
Warning: mupdf 1.18.0_1 is already installed, it's just not linked
You can use `brew link mupdf` to link this version.
❯ brew link mupdf
Linking /usr/local/Cellar/mupdf/1.18.0_1... 11 symlinks created
❯ brew install zathura-pdf-mupdf
==> Installing zathura-pdf-mupdf from zegervdv/zathura
==> Downloading https://github.com/pwmt/zathura-pdf-mupdf/archive/0.3.6.tar.gz
Already downloaded: ../Library/Caches/Homebrew/downloads/4cab0906e69aad193ca8622c52fa274962566ec6bafd253f73b147263576d998--zathura-pdf-mupdf-0.3.6.tar.gz
==> mkdir build
==> meson build --prefix /usr/local/Cellar/zathura-pdf-mupdf/0.3.6
==> cd build && ninja && ninja install
==> Caveats
      To enable this plugin you will need to link it in place.
      First create the plugin directory if it does not exist yet:
        $ mkdir -p $(brew --prefix zathura)/lib/zathura
      Then link the .dylib to the directory:
        $ ln -s $(brew --prefix zathura-pdf-mupdf)/libpdf-mupdf.dylib $(brew --prefix zathura)/lib/zathura/libpdf-mupdf.dylib

      More information as to why this is needed: https://github.com/zegervdv/homebrew-zathura/issues/19
==> Summary
🍺  /usr/local/Cellar/zathura-pdf-mupdf/0.3.6: 8 files, 35.2MB, built in 10 seconds
❯
❯ mkdir -p $(brew --prefix zathura)/lib/zathura
❯ ln -s $(brew --prefix zathura-pdf-mupdf)/libpdf-mupdf.dylib $(brew --prefix zathura)/lib/zathura/libpdf-mupdf.dylib
```

**Comment by zegervdv** [comment]
Thanks for testing. I just pushed an updated formula so the manual linking should not be needed anymore.

**Comment by abcarvalho** [comment]
Great! I uninstalled zathura and its dependencies, cleanup the files, re-tapped your cask and reinstalled everything. It all went smooth. No problems this time.

**Comment by emninger** [comment]
Ok, thanks to you both. Fine so far ...
But now, starting zathura, i get this error:

`error: plugin: filetype already registered: com.adobe.pdf`

**Comment by zegervdv** [comment]
Do you have the poppler plug-in installed as well?

**Comment by windowswithoutborders** [comment]
just wanted to chime in and say I installed the poppler version first but then saw the mupdf version was available and of course that's what I need for epub. Can I suggest updating the installation instructions to make it a little more clear? Anyways, really happy to have zathura on macos! Thanks!

**Comment by deepimpactmir** [comment]
Can't seem to install zathura-pdf-mupdf. Installation fails with this error

```
❯ brew install zathura-pdf-mupdf
==> Downloading https://github.com/pwmt/zathura-pdf-mupdf/archive/0.3.7.tar.gz
Already downloaded: /Users/jeremytohhw/Library/Caches/Homebrew/downloads/75fcecb8c53b408fd61d2764cdc99ff0fd551f7a42dc7afd4b7324c6e5ed1c38--zathura-pdf-mupdf-0.3.7.tar.gz
==> Installing zathura-pdf-mupdf from zegervdv/zathura
==> meson --prefix=/opt/homebrew/Cellar/zathura-pdf-mupdf/0.3.7_1 --libdir=/opt/homebrew/Cellar/zathura-pdf-mupdf/0.3.7_1/lib --buildtype=release --wrap-mode=nofallback ..
==> ninja
Last 15 lines from /Users/jeremytohhw/Library/Logs/Homebrew/zathura-pdf-mupdf/02.ninja:
[6/11] Compiling C object libpdf-mupdf.dylib.p/zathura-pdf-mupdf_image.c.o
[7/11] Compiling C object libpdf-mupdf.dylib.p/zathura-pdf-mupdf_page.c.o
[8/11] Compiling C object libpdf-mupdf.dylib.p/zathura-pdf-mupdf_search.c.o
FAILED: libpdf-mupdf.dylib.p/zathura-pdf-mupdf_search.c.o
clang -Ilibpdf-mupdf.dylib.p -I. -I.. -I/opt/homebrew/Cellar/libffi/3.4.2/include -I/opt/homebrew/Cellar/libpng/1.6.37/include/libpng16 -I/opt/homebrew/opt/freetype/include/freetype2 -I/opt/homebrew/Cellar/fontconfig/2.14.0/include -I/opt/homebrew/Cellar/pcre/8.45/include -I/opt/homebrew/Cellar/glib/2.72.3/include/gio-unix-2.0 -I/opt/homebrew/Cellar/glib/2.72.3/include -I/opt/homebrew/Cellar/glib/2.72.3/include/glib-2.0 -I/opt/homebrew/Cellar/glib/2.72.3/lib/glib-2.0/include -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/Cellar/libxau/1.0.9/include -I/opt/homebrew/Cellar/libxdmcp/1.1.3/include -I/opt/homebrew/Cellar/libxcb/1.15/include -I/opt/homebrew/Cellar/libx11/1.8.1/include -I/opt/homebrew/Cellar/libxext/1.3.4/include -I/opt/homebrew/Cellar/libxrender/0.9.10/include -I/opt/homebrew/Cellar/pixman/0.40.0/include/pixman-1 -I/opt/homebrew/Cellar/cairo/1.16.0_5/include/cairo -I/opt/homebrew/Cellar/graphite2/1.3.14/include -I/opt/homebrew/Cellar/harfbuzz/5.1.0/include/harfbuzz -I/opt/homebrew/Cellar/jpeg-turbo/2.1.3/include -I/opt/homebrew/Cellar/libtiff/4.4.0_1/include -I/opt/homebrew/Cellar/gdk-pixbuf/2.42.8_1/include/gdk-pixbuf-2.0 -I/opt/homebrew/Cellar/fribidi/1.0.12/include/fribidi -I/opt/homebrew/Cellar/pango/1.50.8/include/pango-1.0 -I/opt/homebrew/Cellar/atk/2.38.0/include/atk-1.0 -I/opt/homebrew/Cellar/libepoxy/1.5.10/include -I/opt/homebrew/Cellar/gtk+3/3.24.34/include/gtk-3.0 -I/opt/homebrew/Cellar/girara/HEAD-e17dd2f/include -I/opt/homebrew/Cellar/zathura/HEAD-3a6fea5/include -I/opt/homebrew/Cellar/xorgproto/2022.1/include -fcolor-diagnostics -Wall -Winvalid-pch -Wextra -Wpedantic -std=c11 -O3 -DVERSION_MAJOR=0 -DVERSION_MINOR=3 -DVERSION_REV=7 -D_DEFAULT_SOURCE -Werror=implicit-function-declaration -Werror=vla -fvisibility=hidden -MD -MQ libpdf-mupdf.dylib.p/zathura-pdf-mupdf_search.c.o -MF libpdf-mupdf.dylib.p/zathura-pdf-mupdf_search.c.o.d -o libpdf-mupdf.dylib.p/zathura-pdf-mupdf_search.c.o -c ../zathura-pdf-mupdf/search.c
../zathura-pdf-mupdf/search.c:44:39: error: too few arguments to function call, expected 6, have 5
      text, hit_bbox, N_SEARCH_RESULTS);
                                      ^
/opt/homebrew/include/mupdf/fitz/structured-text.h:248:5: note: 'fz_search_stext_page' declared here
int fz_search_stext_page(fz_context *ctx, fz_stext_page *text, const char *needle, int *hit_mark, fz_quad *hit_bbox, int hit_max);
    ^
1 error generated.
[9/11] Compiling C object libpdf-mupdf.dylib.p/zathura-pdf-mupdf_render.c.o
[10/11] Compiling C object libpdf-mupdf.dylib.p/zathura-pdf-mupdf_utils.c.o
ninja: build stopped: subcommand failed.

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
brew install zathura-pdf-mupdf fails https://github.com/zegervdv/homebrew-zathura/issues/66
```

**Comment by PerpetualCreativity** [comment]
Getting the same error as deepimpactmir. It [looks like](https://git.pwmt.org/pwmt/zathura-pdf-mupdf/-/issues/29) it's fixed in the develop branch.

**Comment by PerpetualCreativity** [comment]
Since upstream has fixed the last reported bug in this thread, I haven't had issues installing or running zathura with mupdf.

I think this issue can be closed.

**Comment by TheRealSoundWave** [comment]
No it can't.

```
ninja
[6/11] Compiling C object libpdf-mupdf.so.p/zathura-pdf-mupdf_search.c.o
FAILED: libpdf-mupdf.so.p/zathura-pdf-mupdf_search.c.o 
cc -Ilibpdf-mupdf.so.p -I. -I.. -I/home/soundwave/.local/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/uuid -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/x86_64-linux-gnu -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/at-spi-2.0 -I/usr/include/json-c -I/usr/include/openjpeg-2.4 -I/usr/include/leptonica -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=c11 -g -fPIC -pthread -DVERSION_MAJOR=0 -DVERSION_MINOR=4 -DVERSION_REV=0 -D_DEFAULT_SOURCE -Werror=implicit-function-declaration -Werror=vla -fvisibility=hidden -MD -MQ libpdf-mupdf.so.p/zathura-pdf-mupdf_search.c.o -MF libpdf-mupdf.so.p/zathura-pdf-mupdf_search.c.o.d -o libpdf-mupdf.so.p/zathura-pdf-mupdf_search.c.o -c ../zathura-pdf-mupdf/search.c
../zathura-pdf-mupdf/search.c: In function ‘pdf_page_search_text’:
../zathura-pdf-mupdf/search.c:44:19: warning: passing argument 5 of ‘fz_search_stext_page’ makes integer from pointer without a cast [-Wint-conversion]
   44 |       text, NULL, hit_bbox, N_SEARCH_RESULTS);
      |                   ^~~~~~~~
      |                   |
      |                   fz_quad *
In file included from /usr/include/mupdf/fitz.h:70,
                 from ../zathura-pdf-mupdf/plugin.h:10,
                 from ../zathura-pdf-mupdf/search.c:7:
/usr/include/mupdf/fitz/structured-text.h:247:104: note: expected ‘int’ but argument is of type ‘fz_quad *’
  247 | int fz_search_stext_page(fz_context *ctx, fz_stext_page *text, const char *needle, fz_quad *quads, int max_quads);
      |                                                                                                    ~~~~^~~~~~~~~
../zathura-pdf-mupdf/search.c:43:21: error: too many arguments to function ‘fz_search_stext_page’
   43 |   int num_results = fz_search_stext_page(mupdf_page->ctx, mupdf_page->text,
      |                     ^~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/mupdf/fitz.h:70,
                 from ../zathura-pdf-mupdf/plugin.h:10,
                 from ../zathura-pdf-mupdf/search.c:7:
/usr/include/mupdf/fitz/structured-text.h:247:5: note: declared here
  247 | int fz_search_stext_page(fz_context *ctx, fz_stext_page *text, const char *needle, fz_quad *quads, int max_quads);
      |     ^~~~~~~~~~~~~~~~~~~~
[10/11] Compiling C object libpdf-mupdf.so.p/zathura-pdf-mupdf_document.c.o
ninja: build stopped: subcommand failed.
 soundwave  ~  sw.workspace  zathura-pdf-mupdf-0.4.0  build  1  ninja
[1/2] Compiling C object libpdf-mupdf.so.p/zathura-pdf-mupdf_search.c.o
FAILED: libpdf-mupdf.so.p/zathura-pdf-mupdf_search.c.o 
cc -Ilibpdf-mupdf.so.p -I. -I.. -I/home/soundwave/.local/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/uuid -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/x86_64-linux-gnu -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/at-spi-2.0 -I/usr/include/json-c -I/usr/include/openjpeg-2.4 -I/usr/include/leptonica -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=c11 -g -fPIC -pthread -DVERSION_MAJOR=0 -DVERSION_MINOR=4 -DVERSION_REV=0 -D_DEFAULT_SOURCE -Werror=implicit-function-declaration -Werror=vla -fvisibility=hidden -MD -MQ libpdf-mupdf.so.p/zathura-pdf-mupdf_search.c.o -MF libpdf-mupdf.so.p/zathura-pdf-mupdf_search.c.o.d -o libpdf-mupdf.so.p/zathura-pdf-mupdf_search.c.o -c ../zathura-pdf-mupdf/search.c
../zathura-pdf-mupdf/search.c: In function ‘pdf_page_search_text’:
../zathura-pdf-mupdf/search.c:44:19: warning: passing argument 5 of ‘fz_search_stext_page’ makes integer from pointer without a cast [-Wint-conversion]
   44 |       text, NULL, hit_bbox, N_SEARCH_RESULTS);
      |                   ^~~~~~~~
      |                   |
      |                   fz_quad *
In file included from /usr/include/mupdf/fitz.h:70,
                 from ../zathura-pdf-mupdf/plugin.h:10,
                 from ../zathura-pdf-mupdf/search.c:7:
/usr/include/mupdf/fitz/structured-text.h:247:104: note: expected ‘int’ but argument is of type ‘fz_quad *’
  247 | int fz_search_stext_page(fz_context *ctx, fz_stext_page *text, const char *needle, fz_quad *quads, int max_quads);
      |                                                                                                    ~~~~^~~~~~~~~
../zathura-pdf-mupdf/search.c:43:21: error: too many arguments to function ‘fz_search_stext_page’
   43 |   int num_results = fz_search_stext_page(mupdf_page->ctx, mupdf_page->text,
      |                     ^~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/mupdf/fitz.h:70,
                 from ../zathura-pdf-mupdf/plugin.h:10,
                 from ../zathura-pdf-mupdf/search.c:7:
/usr/include/mupdf/fitz/structured-text.h:247:5: note: declared here
  247 | int fz_search_stext_page(fz_context *ctx, fz_stext_page *text, const char *needle, fz_quad *quads, int max_quads);
      |     ^~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
```
